namespace Ube.Domain.Enums.Notifications;

public enum NotificationType
{
    // Legacy values retained for backward compatibility with existing stored data.
    NewBookingRequest = 1,
    BookingConfirmation = 2,
    Cancellation = 3,
    PaymentReceived = 4,
    PayoutProcessed = 5,
    PaymentFailed = 6,
    NewReview = 7,
    ReviewResponse = 8,
    SecurityAlert = 9,
    AccountUpdate = 10,
    VendorApproved = 11,
    RefundPending = 12,
    SystemMaintenance = 13,
    GatewayError = 14,
    RevenueTargetAchieved = 15,

    // Admin notifications
    AdminNewVendorRegistered = 101,
    AdminNewListingSubmitted = 102,
    AdminVendorRequestApproval = 103,
    AdminNewBookingCreated = 104,
    AdminBookingCancellation = 105,
    AdminPaymentIssue = 106,
    AdminCustomerReportSubmitted = 107,
    AdminListingReported = 108,
    AdminVendorAccountSuspended = 109,
    AdminListingApprovalRequired = 110,
    AdminListingUpdateRequiresReview = 111,
    AdminNewCustomerRegistration = 112,
    AdminRefundRequest = 113,
    AdminSystemAlert = 114,

    // Vendor notifications
    VendorListingsApproved = 201,
    VendorListingsRejected = 202,
    VendorListingsUpdateApproved = 203,
    VendorListingsUpdateRejected = 204,
    VendorNewBookingReceived = 205,
    VendorBookingConfirmed = 206,
    VendorBookingCancelledByCustomer = 207,
    VendorBookingRescheduled = 208,
    VendorPaymentReceived = 209,
    VendorPaymentFailed = 210,
    VendorRefundRequested = 211,
    VendorRefundProcessed = 212,
    VendorNewCustomerReview = 213,
    VendorLowRatingReceived = 214,
    VendorAccountApproved = 215,
    VendorAccountRejected = 216,
    VendorAccountSuspended = 217,
    VendorListingExpired = 218,
    VendorSystemAnnouncement = 219,

    // Customer notifications
    CustomerBookingConfirmed = 301,
    CustomerBookingPending = 302,
    CustomerBookingRejected = 303,
    CustomerBookingCancelledByVendor = 304,
    CustomerBookingCancelledByCustomer = 305,
    CustomerBookingRescheduled = 306,
    CustomerBookingReminder = 307,
    CustomerPaymentSuccessful = 308,
    CustomerPaymentFailed = 309,
    CustomerRefundRequested = 310,
    CustomerRefundApproved = 311,
    CustomerRefundRejected = 312,
    CustomerRefundProcessed = 313,
    CustomerBookingCompleted = 314,
    CustomerReviewReminder = 315,
    CustomerReviewSubmitted = 316,
    CustomerBookingStatusChanged = 317,
    CustomerAccountVerification = 318,
    CustomerSystemAnnouncement = 319,
    CustomerPromotionAndOfferAvailable = 320
}
