using Microsoft.AspNetCore.Http;
using Ube.Application.Features.Listings;

namespace Ube.Api.Controllers.Listings;

/// <summary>
/// Multipart form used when creating a listing. Images are uploaded as files;
/// their public URLs are generated by the API and are not supplied by clients.
/// </summary>
public sealed class CreateListingFormRequest
{
    public Guid CategoryId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string? Description { get; set; }
    public decimal Price { get; set; }
    public string Currency { get; set; } = "LKR";
    public string? Location { get; set; }
    public bool IsActive { get; set; } = true;
    public List<IFormFile> Images { get; set; } = new();
    public List<string> Tags { get; set; } = new();
    public string? CancellationPolicy { get; set; }
    public HotelDetailsDto? HotelDetails { get; set; }
    public RestaurantDetailsDto? RestaurantDetails { get; set; }
    public EventDetailsDto? EventDetails { get; set; }
    public CarRentalDetailsDto? CarRentalDetails { get; set; }
    public ActivityDetailsDto? ActivityDetails { get; set; }
    public List<ListingCustomFieldValueInputDto> CustomFieldValues { get; set; } = new();

    public CreateListingRequest ToApplicationRequest(List<string> imageUrls) => new()
    {
        CategoryId = CategoryId,
        Title = Title,
        Description = Description,
        Price = Price,
        Currency = Currency,
        Location = Location,
        IsActive = IsActive,
        Images = imageUrls,
        Tags = Tags,
        CancellationPolicy = CancellationPolicy,
        HotelDetails = HotelDetails,
        RestaurantDetails = RestaurantDetails,
        EventDetails = EventDetails,
        CarRentalDetails = CarRentalDetails,
        ActivityDetails = ActivityDetails,
        CustomFieldValues = CustomFieldValues
    };
}
